"""Added timer and answers areas

Revision ID: 4383e3378773
Revises: 135f9e096d6c
Create Date: 2025-04-14 10:52:42.635182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4383e3378773'
down_revision: Union[str, None] = '135f9e096d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizquests', sa.Column('time_below', sa.Integer(), nullable=False))
    op.add_column('quizquests', sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('quizs', sa.Column('timer', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizs', 'timer')
    op.drop_column('quizquests', 'answers')
    op.drop_column('quizquests', 'time_below')
    # ### end Alembic commands ###
