"""add_new_fields_to_quiz

Revision ID: 6bec7ffbd597
Revises: dd626e00bbd6
Create Date: 2025-05-15 23:43:20.040990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bec7ffbd597'
down_revision: Union[str, None] = 'dd626e00bbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizquests', sa.Column('manual_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quizquests', 'manuals', ['manual_id'], ['id'])
    op.add_column('quizs', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('quizs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('quizs', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('quizs', sa.Column('min_pass_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizs', 'min_pass_percentage')
    op.drop_column('quizs', 'max_attempts')
    op.drop_column('quizs', 'is_active')
    op.drop_column('quizs', 'deadline')
    op.drop_constraint(None, 'quizquests', type_='foreignkey')
    op.drop_column('quizquests', 'manual_id')
    # ### end Alembic commands ###
